### ISSUE TITLE
Support for AppCode

### ISSUE THREAD

**Issue by ramonpoca** [Andrevus/jetbrains-targetprocess-tasks#3]
Hi there,

AppCode seems to be using a lower JDK (1.6) than the released plugin. 
Throws an exception: Unsupported major.minor version 51.0.

AppCode EAP has a build with JDK 1.8, but could you lower the release compatibility to 1.6/generate a release with 1.6 SDK compatibilty?

**Comment by andrevus** [comment]
you can try to use this code to generate plugin which will be compatible with your version.
